image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.11

environment:
  GITHUB_TOKEN:
    secure: Pi8XNRobS/Bi65fFy0BBFxat/679BFHKrCfK8dZ3pHHrvMKLWNpOX3TfdBOMgBkU

install:
- python.exe -m pip install --upgrade pip
- pip install pandas
- pip install -r requirements.txt


test: off

# Publish artifacts to GitHub Releases on "tag" builds --icon dataicon.png 
deploy:
  release: JSONToCSV-v$(APPVEYOR_BUILD_VERSION)
  description: 'JSONToCSV Tool for ETL'
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    branch: main
    APPVEYOR_REPO_TAG_MAIN: true
    APPVEYOR_REPO_TAG: true


#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a JsonToCSV-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: JsonToCSV-windows.zip
 
  build_script:
  - flet pack main.py --name JsonToCSV --add-data "assets;assets" --product-name JsonToCSV --product-version "0.0.1" --copyright "Copyright (c) 2024 GKTwin Apps"

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf JsonToCSV-macos.tar.gz -C dist JsonToCSV.app

  artifacts:
  - path: JsonToCSV-macos.tar.gz

  build_script:
  - flet pack main.py --name JsonToCSV --add-data "assets:assets" --product-name JsonToCSV --product-version "0.0.1" --copyright "Copyright (c) 2024 GKTwin Apps"

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf JsonToCSV-linux.tar.gz -C dist JsonToCSV

  artifacts:
  - path: JsonToCSV-linux.tar.gz

  build_script:
  - flet pack main.py --name JsonToCSV --add-data "assets:assets" --product-name JsonToCSV --product-version "0.0.1" --copyright "Copyright (c) 2024 GKTwin Apps"
